[build]
  # Leave base empty or "." so Netlify sees the whole repo
  base = "."
  
  # Reach into the client folder to build
  command = "cd ntu-stars && bun run build"
  
  # Nuxt 3 outputs the static files here
  publish = "ntu-stars/output"

[functions]
  # If you want your 'server-api' to be deployed as Netlify Functions
  directory = "ntu-services"